# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c608083118bb4c8b0d51728411b44f7e8b7f7382edc18069dbdf55ef5aea28af1d4a60203eef0035d3e7eee7d68b2682d8422340f37f235b4257104e65737483

test:
  secret_key_base: 53393581eabd20d5ff3ceaf2458534db68db21aba4357931a8066959bd225adeb09c3d3eefbbb5094c3be6320a4f418aa9e432af9f1290c9b86f9d288559a87a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
